name: flutter_shop
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^2.1.13
  flutter_swiper : ^1.1.6
  flutter_screenutil: ^0.5.3
  url_launcher: ^5.1.2
  flutter_easyrefresh: ^2.0.1
  provide: ^1.0.2
  fluttertoast: ^3.1.0
  fluro: "^1.5.1"
  shared_preferences: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

